[package]
name = "ydh-desktop"
version = "0.1.0"
edition = "2021"

[dependencies]
tauri = { version = "1", features = ["shell-open"] }
serde = { version = "1", features = ["derive"] }

[build-dependencies]
tauri-build = "1"
